# ARMAS DE COMBATE A MANO -------------------------------------------------------------------------------------------------
[[items]]
name = "Espada"
type = "MELEE_WEAPON"
minimalDamage = 2
maximunDamage = 5
sellingPrice = 5
purchasePrice = 10

[[items]]
name = "Hacha"
type = "MELEE_WEAPON"
minimalDamage = 4
maximunDamage = 5
sellingPrice = 6
purchasePrice = 12

[[items]]
name = "Martillo"
type = "MELEE_WEAPON"
minimalDamage = 1
maximunDamage = 9
sellingPrice = 5
purchasePrice = 10

#OBJETOS MAGICOS -------------------------------------------------------------------------------------------------------------
[[items]]
name = "Vara de fresno"
type = "MAGICAL_OBJECT"
subtype = "ATTACK"
minimalDamage = 2
maximunDamage = 4
mana_cost = 5
sellingPrice = 10
purchasePrice = 15

[[items]]
name = "Báculo nudoso"
type = "MAGICAL_OBJECT"
subtype = "ATTACK"
range = 4
minimalDamage = 4
maximunDamage = 8
mana_cost = 15
sellingPrice = 6
purchasePrice = 12

[[items]]
name = "Báculo engarzado"
type = "MAGICAL_OBJECT"
subtype = "ATTACK"
range = 8
minimalDamage = 8
maximunDamage = 20
mana_cost = 30
sellingPrice = 15
purchasePrice = 20

[[items]]
name = "Flauta élfica"
type = "MAGICAL_OBJECT"
subtype = "HEALING"
range = 3
mana_cost = 100
sellingPrice = 15
purchasePrice = 20

# ARMAS DE COMBATE A DISTANCIA -------------------------------------------------------------------------------------------------------
[[items]]
name = "Arco simple"
type = "RANGED_WEAPON"
range = 6
minimalDamage = 1
maximunDamage = 4
sellingPrice = 5
purchasePrice = 10

[[items]]
name = "Arco compuesto"
type = "RANGED_WEAPON"
range = 8
minimalDamage = 4
maximunDamage = 16
sellingPrice = 8
purchasePrice = 18
 

# OBJETOS DE DEFENSA ------ -----------------------------------------------------------------------------------------------
[[items]]
name = "Armadura de cuero"
type = "DEFENSE_EQUIPMENT"
subtype = ""
minimal_defense = 2
maximun_defense = 6
sellingPrice = 4
purchasePrice = 6

[[items]]
name = "Armadura de placas"
type = "DEFENSE_EQUIPMENT"
minimal_defense = 15
maximun_defense = 30
sellingPrice = 6
purchasePrice = 8

[[items]]
name = "Tunica azul"
type = "DEFENSE_EQUIPMENT"
minimal_defense = 6
maximun_defense = 10
sellingPrice = 6
purchasePrice = 10

[[items]]
name = "Capucha"
type = "DEFENSE_EQUIPMENT"
minimal_defense = 1 
maximun_defense = 4
sellingPrice = 4
purchasePrice = 6

[[items]]
name = "Casco de hierro"
type = "DEFENSE_EQUIPMENT"
minimal_defense = 4
maximun_defense = 8
sellingPrice = 5
purchasePrice = 10


[[items]]
name = "Escudo de tortuga"
type = "DEFENSE_EQUIPMENT"
minimal_defense = 1
maximun_defense = 2
sellingPrice = 5
purchasePrice = 10


[[items]]
name = "Escudo de hierro"
type = "DEFENSE_EQUIPMENT"
minimal_defense = 1
maximun_defense = 4
sellingPrice = 5
purchasePrice = 10


[[items]]
name = "Sombrero mágico"
type = "DEFENSE_EQUIPMENT"
minimal_defense = 4 
maximun_defense = 12
sellingPrice = 5
purchasePrice = 10

# POCIONES ----------------------------------------------------------------------------------------------------------------- 
[[items]]
name = "poción restauradora de vida"
type = "POTION"
subtype = "LIFE"
sellingPrice = 5
purchasePrice = 10

[[items]]
name = "poción restauradora de mana"
type = "POTION"
subtype = "MANA"
sellingPrice = 5
purchasePrice = 10


# NOTAS IMPORTANTES: 
#    - Tal vez los id sean innecesarios y solo baste con los types (los id deberia ser en tiempo de ejecucion para identi-
#   ficar que items ha sido tomado, vendido, comprado, encontrado)
