# ARMAS DE COMBATE A MANO -------------------------------------------------------------------------------------------------

[[items]]
#idItem = 1 # Espada
name = "Espada"
type = "MELEE_WEAPON"
minimalDamage = 2
maximunDamage = 5
sellingPrice = 5
purchasePrice = 10

[[items]]
#idItem = 2 # Hacha 
name = "Hacha"
type = "MELEE_WEAPON"
minimalDamage = 4
maximunDamage = 5
sellingPrice = 6
purchasePrice = 12

[[items]]
#idItem = 3 # Martillo
name = "Martillo"
type = "MELEE_WEAPON"
minimalDamage = 1
maximunDamage = 9
sellingPrice = 5
purchasePrice = 10

#OBJETOS MAGICOS -------------------------------------------------------------------------------------------------------------
[[items]]
#idItem = 4 # vara de fresno
name = "Vara de fresno"
type = "MAGICAL_OBJECT"
subtype = "ATTACK"
minimalDamage = 2
maximunDamage = 4
mana_cost = 5
sellingPrice = 10
purchasePrice = 15

[[items]]
#idItem = 5 # Baculo nudoso 
name = "Báculo nudoso"
type = "MAGICAL_OBJECT"
subtype = "ATTACK"
range = 4
minimalDamage = 4
maximunDamage = 8
mana_cost = 15
sellingPrice = 6
purchasePrice = 12

[[items]]
#idItem = 6 # Baculo engarzado 
name = "Báculo engarzado"
type = "MAGICAL_OBJECT"
subtype = "ATTACK"
range = 8
minimalDamage = 8
maximunDamage = 20
mana_cost = 30
sellingPrice = 15
purchasePrice = 20

[[items]]
#idItem = 7 # flauta elfica 
name = "Flauta élfica"
type = "MAGICAL_OBJECT"
subtype = "HEALING"
range = 3
mana_cost = 100
sellingPrice = 15
purchasePrice = 20

# ARMAS DE COMBATE A DISTANCIA -------------------------------------------------------------------------------------------------------
[[items]]
#idItem = 8 # arco simple 
name = "Arco simple"
type = "RANGED_WEAPON"
range = 6
minimalDamage = 1
maximunDamage = 4
sellingPrice = 5
purchasePrice = 10

[[items]]
#idItem = 9 # arco compuesto
name = "Arco compuesto"
type = "RANGED_WEAPON"
range = 8
minimalDamage = 4
maximunDamage = 16
sellingPrice = 8
purchasePrice = 18
 

# OBJETOS DE DEFENSA ------ -----------------------------------------------------------------------------------------------
[[items]]
#idItem = 10 # armadura de cuero
name = "Armadura de cuero"
type = "DEFENSE_EQUIPMENT"
subtype = ""
minimalDefense = 2
maximunDefense = 6
sellingPrice = 4
purchasePrice = 6

[[items]]
#idItem = 11 # armadura de placas
name = "Armadura de placas"
type = "DEFENSE_EQUIPMENT"
minimalDefense = 15
maximunDefense = 30
sellingPrice = 6
purchasePrice = 8

[[items]]
#idItem = 12 # Tunica azul 
name = "Tunica azul"
type = "DEFENSE_EQUIPMENT"
minimalDefense = 6
maximunDefense = 10
sellingPrice = 6
purchasePrice = 10

[[items]]
#idItem = 13 # capucha
name = "Capucha"
type = "DEFENSE_EQUIPMENT"
minimalDefense = 1 
maximunDefense = 4
sellingPrice = 4
purchasePrice = 6

[[items]]
#idItem = 14 # casco de hierro 
name = "Casco de hierro"
type = "DEFENSE_EQUIPMENT"
minimalDefense = 4
maximunDefense = 8
sellingPrice = 5
purchasePrice = 10

[[items]]
#idItem = 15 # escudo de tortuga
name = "Escudo de tortuga"
type = "DEFENSE_EQUIPMENT"
minimalDefense = 1
maximunDefense = 2
sellingPrice = 5
purchasePrice = 10

[[items]]
#idItem = 16 # escudo de hierro 
name = "Escudo de hierro"
type = "DEFENSE_EQUIPMENT"
minimalDefense = 1
maximunDefense = 4
sellingPrice = 5
purchasePrice = 10

[[items]]
#idItem = 17 # sombrero magico
name = "Sombrero mágico"
type = "DEFENSE_EQUIPMENT"
minimalDefense = 4 
maximunDefense = 12
sellingPrice = 5
purchasePrice = 10

# POCIONES ----------------------------------------------------------------------------------------------------------------- 
[[items]]
#idItem = 18 # pocion vida
name = "poción restauradora de vida"
type = "POTION"
subtype = "LIFE"
sellingPrice = 5
purchasePrice = 10

[[items]]
#idItem = 19 # pocion vida
name = "poción restauradora de mana"
type = "POTION"
subtype = "MANA"
sellingPrice = 5
purchasePrice = 10

