# ARMAS DE COMBATE A MANO -------------------------------------------------------------------------------------------------

[[items]]
idItem = 1 # Espada
name = "Espada"
description = "MELEE_WEAPON"
body_part = 3 #HAND
classif = 1 #ATTACK
minimal_damage = 2
maximun_damage = 5
selling_price = 5
purchase_price = 10

[[items]]
idItem = 2 # Hacha 
name = "Hacha"
description = "MELEE_WEAPON"
body_part = 3 #HAND
classif = 1 #ATTACK
minimal_damage = 4
maximun_damage = 5
selling_price = 6
purchase_price = 12

[[items]]
idItem = 3 # Martillo
name = "Martillo"
description = "MELEE_WEAPON"
body_part = 3 #HAND
classif = 1 #ATTACK
minimal_damage = 1
maximun_damage = 9
selling_price = 5
purchase_price = 10

#OBJETOS MAGICOS -------------------------------------------------------------------------------------------------------------
[[items]]
idItem = 4 # vara de fresno
name = "Vara de fresno"
description = "MAGICAL"
body_part = 3 #HAND
classif = 1 #ATTACK
minimal_damage = 2
maximun_damage = 4
mana_cost = 5
range = 4
selling_price = 10
purchase_price = 15

[[items]]
idItem = 5 # Baculo nudoso 
name = "Báculo nudoso"
description = "MAGICAL"
body_part = 3 #HAND
classif = 1 #ATTACK
minimal_damage = 4
maximun_damage = 8
mana_cost = 15
range = 4
selling_price = 6
purchase_price = 12

[[items]]
idItem = 6 # Baculo engarzado 
name = "Báculo engarzado"
description = "MAGICAL"
body_part = 3 #HAND
classif = 1 #ATTACK
minimal_damage = 8
maximun_damage = 20
mana_cost = 30
range = 8
selling_price = 15
purchase_price = 20

[[items]]
idItem = 7 # flauta elfica 
name = "Flauta élfica"
description = "MAGICAL"
body_part = 3 #HAND
classif = 3 #HEALING
mana_cost = 100
range = 3
selling_price = 15
purchase_price = 20

# ARMAS DE COMBATE A DISTANCIA -------------------------------------------------------------------------------------------------------
[[items]]
idItem = 8 # arco simple 
name = "Arco simple"
description = "RANGED_WEAPON"
body_part = 3 #HAND
classif = 1 #ATTACK 
range = 6
minimal_damage = 1
maximun_damage = 4
selling_price = 5
purchase_price = 10

[[items]]
idItem = 9 # arco compuesto
name = "Arco compuesto"
description = "RANGED_WEAPON"
body_part = 3 #HAND
classif = 1 #ATTACK 
range = 8
minimal_damage = 4
maximun_damage = 16
selling_price = 8
purchase_price = 18
 
# OBJETOS DE DEFENSA ------ -----------------------------------------------------------------------------------------------
[[items]]
idItem = 10 # armadura de cuero
name = "Armadura de cuero"
description = "DEFENSE_EQUIPMENT"
body_part = 2 #BACK
classif = 0 #DEFENSE
minimal_defense = 2
maximun_defense = 6
selling_price = 4
purchase_price = 6

[[items]]
idItem = 11 # armadura de placas
name = "Armadura de placas"
description = "DEFENSE_EQUIPMENT"
body_part = 2 #BACK
classif = 0 #DEFENSE
minimal_defense = 15
maximun_defense = 30
selling_price = 6
purchase_price = 8

[[items]]
idItem = 12 # Tunica azul 
name = "Tunica azul"
description = "DEFENSE_EQUIPMENT"
body_part = 2 #BACK
classif = 0 #DEFENSE
minimal_defense = 6
maximun_defense = 10
selling_price = 6
purchase_price = 10

[[items]]
idItem = 13 # capucha
name = "Capucha"
description = "DEFENSE_EQUIPMENT"
body_part = 1 #HEAD
classif = 0 #DEFENSE
minimal_defense = 1 
maximun_defense = 4
selling_price = 4
purchase_price = 6

[[items]]
idItem = 14 # casco de hierro 
name = "Casco de hierro"
description = "DEFENSE_EQUIPMENT"
body_part = 1 #HEAD
classif = 0 #DEFENSE
minimal_defense = 4
maximun_defense = 8
selling_price = 5
purchase_price = 10

[[items]]
idItem = 15 # escudo de tortuga
name = "Escudo de tortuga"
description = "DEFENSE_EQUIPMENT"
body_part = 3 #HAND
classif = 0 #DEFENSE
minimal_defense = 1
maximun_defense = 2
selling_price = 5
purchase_price = 10

[[items]]
idItem = 16 # escudo de hierro 
name = "Escudo de hierro"
description = "DEFENSE_EQUIPMENT"
body_part = 3 #HAND
classif = 0 #DEFENSE
minimal_defense = 1
maximun_defense = 4
selling_price = 5
purchase_price = 10

[[items]]
idItem = 17 # sombrero magico
name = "Sombrero mágico"
description = "DEFENSE_EQUIPMENT"
body_part = 1 #HEAD
classif = 0 #DEFENSE
minimal_defense = 4 
maximun_defense = 12
selling_price = 5
purchase_price = 10

# POCIONES ----------------------------------------------------------------------------------------------------------------- 
[[items]]
idItem = 18 # pocion vida
name = "poción restauradora de vida"
description = "POTION"
body_part = 4 #MOUTH
classif = 3 #HEALING
selling_price = 5
purchase_price = 10

[[items]]
idItem = 19 # pocion vida
name = "poción restauradora de mana"
description = "POTION"
body_part = 4 #MOUTH
classif = 3 #"HEALING"
selling_price = 5
purchase_price = 10

