##-----------------------------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 1 #GOBLIN DE CAMPO
#name = "Goblin de campo"
#attack_range = 4
#hp_max_initial = 40
#minimal_level = 1
#maximun_level = 8
##CAMPO: 5
##--------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 2 #GOBLIN DE BOSQUE
#name = "Goblin de bosque"
#attack_range = 4
#hp_max_initial = 40
#minimal_level = 9
#maximun_level = 14
##FOREST:3
##------------------------------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 3 #ESQUELETO
#name = "Esqueleto"
#attack_range = 3
#hp_max_initial = 80
#minimal_level = 17
#maximun_level = 23
##DESERT:4
##--------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 4 #ESQUELETO GUERRERO
#name = "Esqueleto guerrero"
#attack_range = 3
#hp_max_initial = 100
#minimal_level = 30
#maximun_level = 40
##MAZMORRA:2
##-------------------------------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 5
#name = "Zombie"
#attack_range = 4
#hp_max_initial = 150
#minimal_level = 30
#maximun_level = 40
##MAZMORRA:3
## -------------------------------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 6 #ARANA DE MAZMORA
#name = "Araña de mazmorra"
#attack_range = 4
#hp_max_initial = 60
#minimal_level = 32
#maximun_level = 38
##MAZMORRA:2
##-----------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 7 #ARANA DE CAVERNA
#name = "Araña de carvena"
#attack_range = 4
#hp_max_initial = 60
#id_region = 1 #CAVERNA
#minimal_level = 24
#maximun_level = 30
##--------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 8 #ARANA DE BOSQUE
#name = "Araña de bosque"
#attack_range = 4
#hp_max_initial = 30
#minimal_level = 10
#maximun_level = 15
##FOREST:3
##------------------------------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 9 #ORCO
#name = "Orco"
#attack_range = 6
#hp_max_initial = 100
#minimal_level = 10
#maximun_level = 20
##CAVERN:1
##------------------------------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 10 #GOLEM
#name = "Golem"
#attack_range = 3
#hp_max_initial = 120
#minimal_level = 17
#maximun_level = 22
##DESERT:4
##------------------------------------------------------------------------------------------------------------------------
#[[npcs]]
#id_type = 11 #GOLEM INFERNAL
#name = "Golem infernal"
#attack_range = 3
#hp_max_initial = 120
#minimal_level = 17
#maximun_level = 22
##DESERT:4  #CAVERNA:1
#------------------------------------------------------------------------------------------------
[[npcs]]
id_type = 12
name = "Comerciante"
id_items_store = [1, 2, 3, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]#Puede vender/comprar: cualquier item,menos baculos y varas (hechizos)
#PUEBLO: 7, CITY:6
#------------------------------------------------------------------------------------------------
[[npcs]]
id_type = 13
name = "Sacerdote"
id_items_store = [4, 5, 6, 7, 18, 19]#Puede vender: baculos, varas, pociones
#PUEBLO:7, CITY:6
#----------------------------------------------------------------------------------------------------
[[npcs]]
id_type = 14
name = "Banquero"
#PUEBLO:7, CITY:6
#------------------------------------------------------------------------------------------------
