#REGIONES DONDE PUEDEN APARARECER ESTOS NPCS -> CAMPOS,BOSQUES, DESIERTOS, CAVERNAS, MAZMORRAS
#-----------------------------------------------------------------------------------------------------------------------
[[npcs]]
id = 101
type = "GOBLIN" #puede no ser necesario si ya tengo el id
name = "Goblin"
attackRange = 4
lifeMaxInitial = 40

[[npcs.regions]] #En el campo solo van a aparecer goblin que esten en estos niveles "faciles"
region = "CAMPO"
minimalLevel = 1
maximunLevel = 8

[[npcs.regions]] #En el bosque solo van a aparecer goblin que esten en estos niveles "medios"
region = "BOSQUE"
minimalLevel = 9
maximunLevel = 14
# -------------------------------------------------------------------------------------------------------------------------
[[npcss]]
id = 102
type = "ARAÑA"
name = "Araña"
attackRange = 4 
lifeMaxInitial = 60

[[npcs.regions]] #En las mazmorras solo van a aparecer estas arañas que tiene en estos niveles "dificiles"
region = "MAZMORRA"
minimalLevel = 32
maximunLevel = 38

[[npcs.regions]] #En las cavernas solo van a aparecer estas arañas que tiene en estos niveles "dificiles"
region = "CAVERNA"
minimalLevel = 24
maximunLevel = 30

[[npcs.regions]] #En los bosques solo van a aparecer estas arañas que tiene en estos niveles "medios"
region = "BOSQUE"
minimalLevel = 10
maximunLevel = 15
#------------------------------------------------------------------------------------------------------------------------
[[npcss]]
id = 103
type = "ESQUELETO"
name = "Esqueletos"
attackRange = 3
lifeMaxInitial = 80

[[npcs.regions]] #En el campo solo van a aparecer esqueletos que esten en estos niveles "dificiles"
region = "MAZMORRA"
minimalLevel = 30
maximunLevel = 40

[[npcs.regions]] #En el bosque solo van a aparecer esqueletos que esten en estos niveles "medios-dificiles"
region = "DESIERTO"
minimalLevel = 17
maximunLevel = 23
#------------------------------------------------------------------------------------------------------------------------
[[npcs]]
id = 104
type = "ORCO"
name = "Orco"
attackRange = 6 
lifeMaxInitial = 100

[[npcs.regions]] #En las mazmorras solo van a aparecer orcos que esten en estos niveles "dificiles"
region = "MAZMORRA"
minimalLevel = 31
maximunLevel = 40

[[npcs.regions]] #En las cavernas solo van a aparecer orcos que esten en estos niveles "dificiles"
region = "CAVERNA"
minimalLevel = 25
maximunLevel = 30

[[npcs.regions]] #En el Desierto solo van a aparecer orcos que esten en estos niveles "medio/dificiles"
region = "DESIERTO"
minimalLevel = 17
maximunLevel = 20
#------------------------------------------------------------------------------------------------------------------------
[[npcs]]
id = 105
type = "GOLEM"
name = "Golem"
attackRange = 3
lifeMaxInitial = 120

[[npcs.regions]] #En el desierto solo van a aparecer golem que esten en estos niveles "medio/dificiles"
region = "DESIERTO"
minimalLevel = 17
maximunLevel = 22

[[npcs.regions]] #En las cavernas solo van a aparecer golem que esten en estos niveles "dificiles"
region = "CAVERNA"
minimalLevel = 24
maximunLevel = 30
#-------------------------------------------------------------------------------------------------------------------------
[[npcs]]
id = 106
type = "ZOMBIE"
name = "zombie"
attackRange = 4
lifeMaxInitial = 150

[[npcs.regions]] #En el desierto solo van a aparecer zombies que esten en estos niveles dificiles"
region = "MAZMORRA"
minimalLevel = 30
maximunLevel = 40
#-------------------------------------------------------------------------------------------------------------------------
# NOTAS IMPORTANTES: 
#    - Tal vez los id sean innecesarios y solo baste con los types (los id deberia ser en tiempo de ejecucion para identi-
#   ficar que npc que estaba en tal region fue atacado/vencido/matado)