# LAS CLASES QUE PUEDEN TENER UN PERSONAJE 
[[races]]
id_type = 1
name = "Humano"
life_factor =  4 #factor de vida
recovery_factor = 2 #factor de recuperacion
mana_factor = 4 #factor de mana

[[races.statistics]]
intelligence = 4
constitution = 3
strength = 2
agility = 3
#-----------------------------------------------------------------------------------------------------
[[races]]
id_type = 2
name = "Elfo"
life_factor =  8 # factor de vida
recovery_factor = 3 #factor de recuperacion
mana_factor = 7 #factor de mana

[[races.statistics]]
intelligence = 8
constitution = 3
strength = 2
agility = 7
#-----------------------------------------------------------------------------------------------------
[[races]]
id_type = 3
name = "Enanos"
life_factor = 6  #factor de vida
recovery_factor = 3 #factor de recuperacion
mana_factor = 5 #factor de mana

[[races.statistics]]
intelligence = 4
constitution = 5
strength = 7
agility = 1
#-------------------------------------------------------------------------------------------------------
[[races]]
id_type = 4
name = "Gnomos"
life_factor =  10 # factor de vida
recovery_factor = 2 #factor de recuperacion
mana_factor = 2 #factor de mana

[[races.statistics]]
intelligence = 8
constitution = 7
strength = 5
agility = 5